umask 022

# source all bash include files
for file in ~/.{bash_aliases,bash_exports,bash_prompt,bash_functions}; do
    [ -r "$file" ] && source "$file"
done
unset file

# bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

# rbenv setup
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# nvm setup
if [ -f $(brew --prefix)/opt/nvm/nvm.sh ]; then
	. $(brew --prefix)/opt/nvm/nvm.sh
fi

clear
