alias cd..="cd .."
alias :q="exit"
alias c='clear'
alias t='tar xfv'
alias tj='tar xfjv'
alias tz='tar xfzv'
alias s='screen -r'
alias ls='lsd'
alias l='less'
alias screen='screen -l'
alias df='df -h'
alias su='su --login'
alias psg='ps -ef | grep'
alias fwlog='tail -f /var/log/ipfw.log'
alias v='vim'
alias pwgen="openssl rand -base64 30"
alias C='see'
alias g='git'
alias gl='glances'
alias reboot='sudo /sbin/reboot'
alias nmap='sudo nmap -sS -P0'
alias ipfw='sudo ipfw'
alias flushdns="dscacheutil -flushcache"
alias top='top -R -F -s 2 -o cpu'
alias digall='dig +nocmd +multiline +noall +answer'
alias sshx='ssh -p 4365'
alias d='docker'
alias dm='docker-machine'
alias dcom='docker-compose'
alias week='date +%V'
alias brewu="brew update && brew upgrade && brew cleanup && brew cask cleanup"
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias path='echo -e ${PATH//:/\\n}'
alias push='git push'
alias pull='git pull -r'
alias rsync_hd_music="rsync -auv ~/Music/HiRes --exclude=.DS_Store /Volumes/music/"
alias decode64='base64 -D'

# cvmaker docker 
alias cvmaker="docker-compose -f ~/projects/cvmaker/cvmaker/docker-compose.yml"
alias cvmakerdev="docker-compose -f ~/projects/cvmaker/cvmaker/docker-compose-dev.yml"

# sistrix docker
alias cm="~/projects/sistrix/linkdb/sistrix-crawler-aggregator/sistrix-crawler-automation/bin/cm"
alias cm_dev="CRAWLER_MASTER_HOST=https://cm-dev.007ac9.net ~/projects/sistrix/linkdb/sistrix-crawler-aggregator/sistrix-crawler-automation/bin/cm"
alias cm_prod="CRAWLER_MASTER_HOST=https://cm.007ac9.net ~/projects/sistrix/linkdb/sistrix-crawler-aggregator/sistrix-crawler-automation/bin/cm"
alias crawler="docker-compose -f ~/projects/sistrix/linkdb/sistrix-crawler-aggregator/sistrix-crawler-master/docker-compose-dev.yml"
alias crawleragent="CRAWLER_NAME=$HOSTNAME RABBITMQ_HOST=host.docker.internal SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092 docker-compose -f ~/projects/sistrix/linkdb/sistrix-crawler-aggregator/sistrix-crawler-agent/docker-compose-dev.yml"

# k8s
alias k='kubectl'
alias kx='kubectx'
alias kn='kubens'
alias kubeseal='kubeseal --controller-namespace gitops'
alias kubesealraw='kubeseal --raw --from-file=/dev/stdin --scope cluster-wide'
alias fluxctl='fluxctl --k8s-fwd-ns gitops'
alias logcli='~/projects/go/bin/logcli'
