DOTFILES="$HOME/dotfiles"

# zsh
ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_PLUGINS=(
  macos
  z
  git
  brew
  docker
  gcloud
  helm
  rbenv
  dotenv
  sdk
)

# fzf
export FZF_BINDINGS="/usr/local/opt/fzf/shell/key-bindings.zsh"

# java env
JAVA_8_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
JAVA_11_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"
JAVA_13_HOME="/Library/Java/JavaVirtualMachines/openjdk-13.jdk/Contents/Home"
#export JAVA_HOME=${JAVA_18_HOME}
export IDEA_JDK=${JAVA_13_HOME}

# maven env
export MAVEN_OPTS='-Xmx1024m'

# android
export ANDROID_HOME="/Users/marc/projects/sdks/android-sdk"

# volta (node)
export VOLTA_HOME="$HOME/.volta"

# go
export GOROOT="/usr/local/opt/go/libexec"
export GOPATH="/Users/marc/projects/go"

# spark
export SPARK_HOME="/Users/marc/.sdkman/candidates/spark/current"

# ruby
export RBENV_ROOT=/usr/local/var/rbenv

# gcloud
export CLOUDSDK_PYTHON="/usr/local/opt/python@3.8/libexec/bin/python"
export CLOUDSDK_HOME="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk"

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
export SDKMAN_INIT="$SDKMAN_DIR/bin/sdkman-init.sh"

# paths
export PYTHON_PATH="/usr/local/opt/python@3.8/bin"
export SCRIPTS_PATH="/Users/marc/projects/scripts"
export XCODE_PATH="/Applications/Xcode.app/Contents/Developer/usr/bin"
export ISTIO_PATH="/Users/marc/projects/cloud/istio-1.7.0/bin"

export PATH="${PYTHON_PATH}:/usr/local/bin:${HOME}/bin:${PATH}:${SCRIPTS_PATH}:${XCODE_PATH}:${GOROOT}/bin:${ISTIO_PATH}"

# misc env
export MANPATH="/opt/local/share/man:${MANPATH}"
export EDITOR='/usr/local/bin/vim'
export HISTCONTROL='ignoredups'
export PAGER='less'
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
