DOTFILES="$HOME/dotfiles"

# zsh
ZSH="$HOME/.oh-my-zsh"
#ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_PLUGINS=(
  macos
  z
  zsh-interactive-cd
  copypath
  git
  docker
  gcloud
  helm
  rbenv
  dotenv
  sdk
)

# homebrew
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY=$HOMEBREW_PREFIX
export HOMEBREW_BUNDLE_FILE="${DOTFILES}/brew/Brewfile"

# fzf
export FZF_BINDINGS="${HOMEBREW_PREFIX}/opt/fzf/shell/key-bindings.zsh"
export FZF_COMPLETION="${HOMEBREW_PREFIX}/opt/fzf/shell/completion.zsh"

# maven env
export MAVEN_OPTS='-Xmx1024m'

# android
export ANDROID_HOME="/Users/marc/projects/sdks/android-sdk"

# volta (node)
export VOLTA_HOME="$HOME/.volta"

# go
export GOROOT="${HOMEBREW_PREFIX}/opt/go/libexec"
export GOPATH="/Users/marc/projects/go"

# spark
export SPARK_HOME="/Users/marc/.sdkman/candidates/spark/current"

# ruby
export RBENV_ROOT=${HOMEBREW_PREFIX}/var/rbenv

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
export SDKMAN_INIT="$SDKMAN_DIR/bin/sdkman-init.sh"

# paths
export SCRIPTS_PATH="/Users/marc/projects/scripts"
export XCODE_PATH="/Applications/Xcode.app/Contents/Developer/usr/bin"

export PATH="${HOME}/.local/bin:${HOME}/bin:${PATH}:${SCRIPTS_PATH}:${XCODE_PATH}:${GOROOT}/bin:${GOPATH}/bin"

export MANPATH="${HOMEBREW_PREFIX}/share/man${MANPATH+:$MANPATH}:"
export INFOPATH="${HOMEBREW_PREFIX}/share/info:${INFOPATH:-}"

# misc env
export EDITOR="${HOMEBREW_PREFIX}/bin/vim"
export HISTCONTROL='ignoredups'
export PAGER='less'
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"


#Auto-Complete function for AWSume
export fpath=(~/.awsume/zsh-autocomplete/ $fpath)

export FPATH="${HOMEBREW_PREFIX}/share/zsh/site-functions:${FPATH}"


