plugins=(
  osx
  z
  git
  brew
  docker
  gcloud
  zsh-nvm
  rbenv
  jenv
  dotenv
)

source $ZSH/oh-my-zsh.sh

source $DOTFILES/shell/aliases
source $DOTFILES/shell/functions


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
