# List of ZSH plugins to load is defined in $HOME/.zshenv
plugins=($ZSH_PLUGINS[*])

# Source file if readable
function source_file() {
  local file="$1"
  [ -r "$file" ] && . "$file"
}

source_file $ZSH/oh-my-zsh.sh
source_file $DOTFILES/shell/aliases.sh
source_file $DOTFILES/shell/aliases.local.sh
source_file $DOTFILES/shell/functions.sh
source_file $DOTFILES/shell/exa.sh

# fzf setup
if [[ $- == *i* && -f $FZF_BINDINGS ]]; then
  source $FZF_BINDINGS
fi
if [[ $- == *i* && -f $FZF_COMPLETION ]]; then
  source $FZF_COMPLETION 2> /dev/null
fi

# homebrew
[[ -s "$HOMEBREW_PREFIX" ]] && export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH"

# volta (must be after homebrew to work)
[[ -s "$VOLTA_HOME" ]] && export PATH="$VOLTA_HOME/bin:$PATH"

# starship prompt
eval "$(starship init zsh)"

# SDKMAN (THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!)
[[ -s "$SDKMAN_INIT" ]] && source "$SDKMAN_INIT"

unset -f source_file
