# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=($ZSH_PLUGINS[*])

source $ZSH/oh-my-zsh.sh

source $DOTFILES/shell/aliases
source $DOTFILES/shell/functions

# fzf key bindings
if [[ -f $FZF_BINDINGS ]]; then
  source $FZF_BINDINGS
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# NVM
[[ -s "$NVM_INIT" ]] && . "$NVM_INIT"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "$SDKMAN_INIT" ]] && source "$SDKMAN_INIT"
