#!/usr/bin/env zsh

local fzf_opts=""
[[ -n "${1}" ]] && fzf_opts="--filter=${1}"

local target_dir="$( \
    rg --files -u -u -g '**/Makefile' -g '**/.git/config' -g '**/build.gradle' ${EXA_PROJECTS} \
        | rg '^(.*?)/([^/]+)/(.git/config|deploy/Makefile|build.gradle)$' -r '$1/$2:$2' \
        | sort -u -t ':' -k 2,2 \
        | fzf ${fzf_opts} \
            --ansi \
            --delimiter ':' \
            --with-nth 2 \
            --min-height 20 \
            --height ${FZF_TMUX_HEIGHT:-40%} \
            --preview-window right:70%:wrap \
            --preview '
                selection={1}
                readme=$(rg --maxdepth 1 --iglob "readme*" --files "${selection}") || true
                if [[ -n "${readme}" ]] ; then
                    bat -p --color=always "${readme}"
                else
                    ls -l --color=always
                fi
            ' \
        | head -n 1 \
        | cut -d ':' -f 1 \
        2>/dev/null \
)"

if [[ "${2}" == "-" ]] ; then
    echo "${target_dir}"
else
    [[ -n "${target_dir}" ]] && cd "${target_dir}"
fi
