#!/usr/bin/env zsh
#
# mnemonic: [K]ill [P]rocess
# show output of "ps -ef", use [tab] to select one or multiple entries
# press [enter] to kill selected processes and go back to the process list.
# or press [escape] to go back to the process list. Press [escape] twice to exit completely.

(date; ps -ef) | fzf --bind='ctrl-r:reload(date; ps -ef)' \
  --header=$'Press CTRL-R to reload\n\n' --header-lines=2 \
  --preview='echo {}' --preview-window=down,3,wrap \
  --layout=reverse --height=80% | awk '{print $2}' | xargs kill -9

